project_id = "okbuktaggaspnqpzmbyn"

[functions.create-signup-token]
verify_jwt = false

[functions.verify-signup-token]
verify_jwt = false

[functions.verify-creator-password]
verify_jwt = false

[functions.validate-creator-session]
verify_jwt = false

[functions.approve-purchase]
verify_jwt = false

[functions.upload-material]
verify_jwt = false

[functions.get-material-url]
verify_jwt = false

[functions.proxy-material]
verify_jwt = false

[functions.create-material-token]
verify_jwt = false

[functions.manage-push-token]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.notify-booking-change]
verify_jwt = false

[functions.notify-purchase-change]
verify_jwt = false

[functions.s3-upload]
verify_jwt = false

[functions.s3-download]
verify_jwt = false

[functions.unlock-materials]
verify_jwt = false

[functions.ogproduct]
verify_jwt = false

[functions.notify-reschedule-request]
verify_jwt = false

[functions.notify-reschedule-response]
verify_jwt = false

[functions.s3-presign-upload]
verify_jwt = false

[functions.upload-product-media]
verify_jwt = false

[functions.product-media-redirect]
verify_jwt = false

[functions.material-file-sizes]
verify_jwt = false
